##
##  Broadcast - Live Event Video Broadcasting Portal
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

#   [broadcast-client] patch packages
patch-apply
    exit 0

#   [broadcast-client] static code analysis (linting)
lint
    vue-tsc --project etc/tsc.json --noEmit && \
    oxlint --config etc/oxlint.jsonc src && \
    eslint --config etc/eslint.mjs src && \
    stylelint --config etc/stylelint.yaml src/*.styl src/*.vue && \
    htmlhint --config etc/htmlhint.json src/*.html

#   [broadcast-client] static code analysis (linting) with file watching
lint-watch
    nodemon --exec "npm start lint" --watch src --ext html,styl,js,ts,vue

#   [broadcast-client] build component for production
build : lint
    vite --config etc/vite.mts build --mode production

#   [broadcast-client] build component for development
build-dev
    vite --config etc/vite.mts build --mode development

#   [broadcast-client] build component for development (continuous file watching)
build-watch
    cross-env NODE_OPTIONS="--max-old-space-size=4096" \
        vite --config etc/vite.mts build --mode development --watch

#   [broadcast-client] run development server (Vite, with hot module reloading)
dev
    vite --config etc/vite.mts --port 12345

#   [broadcast-client] preview the production build locally
preview
    serve -d --listen 12345 --single dst

#   [broadcast-client] remove regularly built files
clean
    shx rm -rf dst

#   [broadcast-client] remove all built files
distclean : clean
    shx rm -rf node_modules
