##
##  Broadcast - Live Event Video Broadcasting Portal
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

#   [broadcast-server] patch packages
patch-apply
    exit 0

#   [broadcast-server] static code analysis (linting)
lint
    oxlint --config etc/oxlint.jsonc src && \
    eslint --config etc/eslint.mjs src

#   [broadcast-server] static code analysis (linting) with file watching
lint-watch
    nodemon --exec "npm start lint" --watch src --ext ts

#   [broadcast-server] code compilation/transpiling (building)
build
    tsc --project etc/tsc.json

#   [broadcast-server] code compilation/transpiling (building) with file watching
build-watch
    nodemon --exec "npm start build" --watch src --ext ts

#   [broadcast-server] generate database schema migrations from the Drizzle schema
db-generate
    drizzle-kit generate --config etc/drizzle.config.ts

#   [broadcast-server] apply database schema migrations to the database
db-push
    BROADCAST_DB_URL="postgres://broadcast:broadcast@127.0.0.1:5432/broadcast" drizzle-kit push --config etc/drizzle.config.ts

#   [broadcast-server] apply database schema migrations to the database
db-migrate
    BROADCAST_DB_URL="postgres://broadcast:broadcast@127.0.0.1:5432/broadcast" drizzle-kit migrate --config etc/drizzle.config.ts

#   [broadcast-server] run server (from transpiled artifacts)
server
    node dst/app.js --mqtt-url "wss://service:jMm3vSOvcLfQJCQiMBxVz2WESJHUyz8k@127.0.0.1:8443/pr/api/server/"

#   [broadcast-server] run server in development mode (continuous file watching)
dev
    nodemon --watch src --ext ts --exec "tsx src/app.ts"

#   [broadcast-server] remove regularly built files
clean
    shx rm -rf dst

#   [broadcast-server] remove all built files
distclean : clean
    shx rm -rf node_modules
